# Use root/example user/password credentials
version: '3.1'

services:
    web:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        image: novin_web
        restart: unless-stopped
        tty: true
        ports:
            - 9092:80
        working_dir: /var/www/html/
        volumes:
            - ./:/var/www/html/
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./php/apache/apache.conf:/etc/apache2/sites-available/000-default.conf
        links:
            - mysql
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: DB!@#
            MYSQL_USER: novin
            MYSQL_PASSWORD: Saeed@123
            MYSQL_DATABASE: novin
        volumes:
            - mysqldata:/var/lib/mysql
            - ./mysql/:/root
        ports:
            - 3306:3306
        restart: unless-stopped
        tty: true


    adminer:
        image: adminer
        restart: always
        ports:
            - 8083:8080
        links:
            - mysql
volumes:
    mysqldata:
